CATALOGO_AEPD = {
    "Perfilado": [
        "Auditoría manual y automática de la calidad de proceso de perfilado",
        "Cancelar los datos en cuanto no sean precisos para el propósito del tratamiento",
        "Controlar que las variables utilizadas tienen valores suficientemente exactos",
        "Definir dentro del tratamiento casos de uso concretos con fines independientes",
        "Eliminar fines secundarios en el tratamiento",
        "Evaluar la inexistencia de sesgos en el proceso de perfilado",
        "Evitar el tratamiento de datos personales innecesarios",
        "Evitar que los encargados accedan a datos sensibles o a la totalidad de los datos",
        "Formación de los operadores para detectar posibles comportamientos erróneos",
        "Garantizar la no recogida de categorías especiales de datos",
        "Implementar políticas muy restrictivas de cancelación de datos",
        "Incluir mecanismos de transparencia que hagan consciente al interesado",
        "Incluir mecanismos que permitan suspender el tratamiento",
        "Incluir salvaguardas para garantizar la calidad de los datos de entrada",
        "Introducir la supervisión humana en acciones realizadas mediante perfilado",
        "Limitar al máximo el nivel de detalle y la granularidad de los datos",
        "Realizar el tratamiento del perfil en el dispositivo local y no en el servidor",
        "Restringir la comunicación de datos a terceros y usar políticas estrictas"
    ],
    "Evaluación de sujetos": [
        "Cambiar, reordenar o reorganizar las fases del tratamiento",
        "Definir dentro del tratamiento casos de uso concretos con fines independientes",
        "Eliminar alguna fase del tratamiento o fines secundarios",
        "Evitar el tratamiento de datos personales innecesarios",
        "Garantizar intervención humana en tiempo real a solicitud del interesado",
        "Garantizar plazos de ejercicio de derecho en tiempo real o más cortos",
        "Implementar métodos ágiles y efectivos para informar de problemas",
        "Incluir procedimientos para resolución de problemas de acceso en tiempo real",
        "Incluir salvaguardas para garantizar la calidad de los datos de entrada",
        "Limitar al máximo el nivel de detalle utilizado en los tratamientos",
        "Limitar la extensión del tratamiento a sujetos vulnerables",
        "Limitarlo únicamente a finalidades cuyo impacto sea reversible",
        "Mantener separados los conjuntos de datos personales",
        "Orientar el tratamiento a cubrir un menor número de ámbitos"
    ],
    "Predicción": [
        "Cambiar, reordenar o reorganizar las fases del tratamiento",
        "Cancelar los datos en cuanto no sean precisos para el propósito",
        "Definir dentro del tratamiento casos de uso concretos con fines independientes",
        "Eliminar alguna fase del tratamiento o fines secundarios",
        "Evitar el tratamiento de datos personales innecesarios",
        "Evitar que los encargados accedan a datos sensibles",
        "Formación de los operadores para detectar comportamientos erróneos",
        "Garantizar la no recogida de categorías especiales",
        "Implementar políticas muy restrictivas de cancelación de datos",
        "Incluir mecanismos de transparencia explícita y de suspensión",
        "Incluir salvaguardas para garantizar la calidad de los datos de entrada",
        "Limitar al máximo el nivel de detalle, granularidad y exposición",
        "Limitar la categoría de datos generados y recogidos",
        "Mantener separados los conjuntos de datos y restringir a terceros"
    ],
    "Control del empleado": [
        "Cancelar los datos en cuanto no sean precisos para el propósito",
        "Definir dentro del tratamiento casos de uso concretos con fines independientes",
        "Evitar que los encargados accedan a datos sensibles",
        "Formación de los operadores para detectar posibles comportamientos erróneos",
        "Garantizar la no recogida de categorías especiales",
        "Hacer partícipes a los interesados de la auditoría del tratamiento",
        "Implementar políticas muy restrictivas de cancelación de datos",
        "Incluir mecanismos de transparencia explícita y de suspensión",
        "Incluir salvaguardas para garantizar la calidad de los datos de entrada",
        "Limitar al máximo el nivel de detalle utilizado y la granularidad",
        "Limitar los ámbitos en los que se realiza el tratamiento"
    ],
    "Control de acceso a internet": [
        "Cancelar los datos en cuanto no sean precisos para el propósito",
        "Definir dentro del tratamiento casos de uso concretos con fines independientes",
        "Eliminar fines secundarios en el tratamiento",
        "Evitar el tratamiento de datos personales innecesarios",
        "Evitar que los encargados accedan a datos sensibles",
        "Formación de los operadores para detectar comportamientos erróneos",
        "Garantizar la no recogida de categorías especiales",
        "Implementar políticas muy restrictivas de cancelación de datos",
        "Incluir mecanismos de transparencia explícita hacia el empleado",
        "Limitar el tratamiento por encargados y la exposición de los datos",
        "Limitar los ámbitos en los que se realiza el tratamiento",
        "Restringir la comunicación de datos a terceros y usar control estricto"
    ]
}
